# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Island94.org
email: bensheldon@gmail.com
description: > # this means to ignore newlines
  A Lost and Found
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://island94.org" # the base hostname & protocol for your site
twitter_username: bensheldon
github_username:  bensheldon

paginate: 10
paginate_path: "/page-:num/"

exclude:
  - scripts
  - spec
  - vendor # for building on CircleCI or anywhere that installs gems into vendor

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-coffeescript
  - jekyll-paginate

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
