# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Island94.org
email: bensheldon@gmail.com
description: > # this means to ignore newlines
  A Lost and Found
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://island94.org" # the base hostname & protocol for your site
twitter_username: bensheldon
github_username:  bensheldon
repository_url: https://github.com/bensheldon/island94-jekyll

permalink: "/:year/:month/:title"
paginate: 10
paginate_path: "/page/:num/"
defaults:
  - scope:
      path: "page"
    values:
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Rakefile
  - scripts
  - spec
  - vendor # for building on CircleCI or anywhere that installs gems into vendor

plugins:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

whitelist:
  - jekyll-coffeescript
  - jekyll-paginate

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
prose:
  rooturl: '_posts'
  siteurl: 'https://island94.org/'
  media: 'uploads'
  ignore:
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
		  alterable: true
      - name: "title"
        field:
          element: "text"
          label: "title"
